var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                    o o                  T                      ",
   "                         xxxx        S     xxx===xxxx==xxxx  T  T               ",
   "                                   xxxxx                     T  T               ",
   "                                                             T  T     ========  ",
   "  x   S            xxxx                   o o                                x  ",
   "  x   xxx               o                                                    x  ",
   "  x            T                         xxxxx                         D   o x  ",
   "  x          xxxx       o                                                    x  ",
   "  x  @  S  T x  x                                                xxxxx       x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxx=================================xxxxxxx   xxxxxxxxx  ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "  v @                                                                           ",
   "   xxxx      TTTTTTTTT                                                          ",
   "        ! S !                                                                   ",
   "        ! o !                                                                   ",
   "        ! S !                                                                   ",
   "        ! o !               =============                                       ",
   "        ! S !                                     xx                            ",
   "        ! o !             o o       o o                                         ",
   "        ! o !            xxxx        S     xxx===xxxx==xxxx   T  T              ",
   "        !   !                      xxxxx                      T  T              ",
   "                                                              T  T    ========  ",
   "  x   o                                                                      x  ",
   "  x   xxxxxxxxxxxxxxxxx o                                                    x  ",
   "  x                                                                    D   o x  ",
   "  x                     o                                                    x  ",
   "  x SSSSS  T xxxx                                                xxxxx       x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxx=================================xxxxxxx   xxxxxxxxx  ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "  v                                                                             ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                            =============                                       ",
   "                                                  xx                            ",
   "                                    o o                                         ",
   "                                     S     xxx=========xxxx   T  T              ",
   "                            xxx===xxx===xxx                   T  T              ",
   "                       S oT !                                 T  T    ========  ",
   "  x                    xxxx                                                  x  ",
   "  x              S oT !                                                      x  ",
   "  x              xxxx                                                  D   o x  ",
   "  x          S oT!                                                           x  ",
   "  x   @    T xxxx                                                xxxxx       x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxx=================================xxxxxxx   xxxxxxxxx  ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "           o     o  ooooo  ooooo  ooooo  ooooo  ooooo  o   o                    ",
   "            o   o     o    o        o    o   o  o  o    o o                     ",
   "             o o      o    o        o    o   o  ooo      o                      ",
   "      @       o     ooooo  ooooo    o    ooooo  o  o     o                      ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "]
  
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
